@startuml Profile picture upload - Use case
skinparam TitleFontStyle bold

left to right direction
skinparam PackageStyle rect
skinparam TitleFontStyle bold

actor :Web Client\nUser: as user <<Human>>
actor :Azure Blob: as azblob <<Cloud Storage>>


title Profile picture upload - Use case

rectangle "Frontend WebApp" {
    usecase (Login) as uc1
    usecase (Edit profile) as uc2
    usecase (File upload) as uc3
    user -- uc1
    user -- uc2
    user -- uc3
    uc3 -- azblob
}

center footer Copyleft (c) 2019
@enduml